### ISSUE TITLE
AttributeError: type object 'Ftdi' has no attribute 'BITMODE_MCU'

### ISSUE THREAD

**Issue by iDoka** [conchyliculture/Yand#10]
I have issue with using yand on CentOS 7.8 64bit.
Here full log:

```
$ sudo /usr/local/bin/yand_cli.py
Traceback (most recent call last):
  File "/usr/local/bin/yand_cli.py", line 4, in <module>
    __import__('pkg_resources').run_script('yand==20190926', 'yand_cli.py')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/yand-20190926-py3.6.egg/EGG-INFO/scripts/yand_cli.py", line 206, in <module>
  File "/usr/local/lib/python3.6/site-packages/yand-20190926-py3.6.egg/EGG-INFO/scripts/yand_cli.py", line 140, in Main
  File "/usr/local/lib/python3.6/site-packages/yand-20190926-py3.6.egg/yand/nand_interface.py", line 145, in Setup
  File "/usr/local/lib/python3.6/site-packages/yand-20190926-py3.6.egg/yand/ftdi_device.py", line 32, in Setup
AttributeError: type object 'Ftdi' has no attribute 'BITMODE_MCU'

```
This string:
https://github.com/conchyliculture/Yand/blob/master/yand/ftdi_device.py#L32

It seems incompatible version of pyftdi?!

**Comment by iDoka** [comment]
Installing obsolete version of `pyftdi` works for me:

```
wget https://github.com/eblot/pyftdi/archive/v0.30.0.tar.gz
tar xzf v0.29.0.tar.gz
cd pyftdi-0.29.0/pyftdi
sudo cp -a * /usr/local/lib/python3.6/site-packages/pyftdi-0.52.9-py3.6.egg/pyftdi/
```


PS: I left this ticket open, please add version limitations in `requirements.txt`

**Comment by iDoka** [comment]
UPD: only v0.29.0 of pyftdi works

v28 & v30 doesnt works (((

**Comment by conchyliculture** [comment]
I unfortunately don't have access to hardware to test that this is enough to make the code work with v>0.29, but can you try to change this line in `yand/ftdi_device.py`:

```
 diff --git a/yand/ftdi_device.py b/yand/ftdi_device.py
index 6c12367..a78a4c6 100644
--- a/yand/ftdi_device.py
+++ b/yand/ftdi_device.py
@@ -29,7 +29,7 @@ class FtdiDevice:
                 'Could not open FTDI device\n'
                 'Check USB connections')
 
-        self.ftdi.set_bitmode(0, ftdi.Ftdi.BITMODE_MCU)
+        self.ftdi.set_bitmode(0, ftdi.Ftdi.BitMode.MCU)
         self.ftdi.write_data(bytearray([ftdi.Ftdi.DISABLE_CLK_DIV5]))
         self.ftdi.purge_buffers()
         self.ftdi.write_data(bytearray([ftdi.Ftdi.SET_BITS_HIGH, 0x0, 0x1]))
```

**Comment by iDoka** [comment]
@conchyliculture I tried pyftdi v0.52.9 (Jan 11, 2021) with proposed changes in `yand/ftdi_device.py`
I can confirm. It works well!
